<?php
/*********************************\ 
  DO NOT EDIT THIS FILE, PLEASE USE
  THE SETTINGS EDITOR
\*********************************/

$settings['load'] = "0";
$settings['mail_message_id'] = "1";
$settings['mail_parameters'] = "";
$settings['adminemail'] = "webmaster@localhost";
$settings['extraadmininfo'] = "1";
$settings['allowaway'] = "1";
$settings['allowbuddyonly'] = "0";
$settings['allowcustomwarnings'] = "1";
$settings['allowmultipleemails'] = "0";
$settings['pmsallowhtml'] = "0";
$settings['sightml'] = "0";
$settings['multirep'] = "1";
$settings['pmsallowmycode'] = "1";
$settings['sigmycode'] = "1";
$settings['negrep'] = "1";
$settings['neurep'] = "1";
$settings['posrep'] = "1";
$settings['postrep'] = "1";
$settings['pmsallowsmilies'] = "1";
$settings['sigsmilies'] = "1";
$settings['asb_allow_user_disable'] = "1";
$settings['pmsallowimgcode'] = "1";
$settings['sigimgcode'] = "1";
$settings['pmsallowvideocode'] = "1";
$settings['username_method'] = "0";
$settings['subscribeexcerpt'] = "100";
$settings['announcementlimit'] = "2";
$settings['attachthumbh'] = "96";
$settings['attachthumbw'] = "96";
$settings['readparentforums'] = "0";
$settings['autt_cal'] = "1";
$settings['avatardir'] = "images/avatars";
$settings['avatarresizing'] = "auto";
$settings['avataruploadpath'] = "./uploads/avatars";
$settings['boardclosed'] = "0";
$settings['boardclosed_reason'] = "These forums are currently closed for maintenance. Please check back later.";
$settings['bbname'] = "Version 16.12";
$settings['url'] = "http://localhost/fw";
$settings['showphp'] = false;
?>
